set(USERS_LIB users-lib)
set(CONNECTION_LIB connection-lib)
set(DATABASE_OPERATIONS_LIB database-operation-lib)
set(LOGGER_LIB logger-lib)
set(SQLite3_LIB sqlite3-lib)
set(ZMQ_COMMS_LIB ZMQComms-lib)
set(SOCKET_COMMS_LIB socket-comms-lib)
