name: Coverage
on:
  push:
jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build and test this project
        run: |
          cmake . -B build
          cmake --build build --config Debug --target all
          ctest --test-dir build

      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -y gcovr

      - name: Generate coverage report
        run: |
          gcovr -r . --json-pretty -o coverage.json --exclude src/Ext --exclude Tst/googletest
          gcovr -r . --fail-under-line 60 --exclude src/Ext --exclude Tst/googletest || echo "Coverage threshold not met, but continuing."

      - name: Submit coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.json
