name: Coverage
on:
  push:
jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build and test this project
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all
          ctest --test-dir build

      - name: Generate a code coverage report
        uses: threeal/gcovr-action@v1.0.0
